<a href="https://colab.research.google.com/github/rudyanibrahim-rgb/portofolio-data-analyst/blob/main/project_besar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install --upgrade pandas-gbq google-cloud-bigquery google-cloud-bigquery-storage

Requirement already satisfied: pandas-gbq in /usr/local/lib/python3.12/dist-packages (0.30.0)
Collecting pandas-gbq
  Downloading pandas_gbq-0.35.0-py3-none-any.whl.metadata (3.7 kB)
Requirement already satisfied: google-cloud-bigquery in /usr/local/lib/python3.12/dist-packages (3.41.0)
Requirement already satisfied: google-cloud-bigquery-storage in /usr/local/lib/python3.12/dist-packages (2.38.0)
Requirement already satisfied: setuptools in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (75.2.0)
Requirement already satisfied: db-dtypes<2.0.0,>=1.1.1 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.6.0)
Requirement already satisfied: numpy>=1.26.4 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.0.2)
Requirement already satisfied: pandas>=1.5.3 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.2.2)
Requirement already satisfied: pyarrow>=12.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (18.1.0)
Requirement already satisfied: pydata-google-auth>=1.5.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.9.1)
Collecting psutil>=5.9.8 (from pandas-gbq)
  Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl.metadata (22 kB)
Requirement already satisfied: google-api-core<3.0.0,>=2.15.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.30.3)
Requirement already satisfied: google-auth>=2.14.1 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (2.47.0)
Requirement already satisfied: google-auth-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (1.4.0)
Requirement already satisfied: packaging>=22.0.0 in /usr/local/lib/python3.12/dist-packages (from pandas-gbq) (26.2)
Requirement already satisfied: google-cloud-core<3.0.0,>=2.4.1 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.6.0)
Requirement already satisfied: google-resumable-media<3.0.0,>=2.0.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.9.0)
Requirement already satisfied: python-dateutil<3.0.0,>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.9.0.post0)
Requirement already satisfied: requests<3.0.0,>=2.21.0 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery) (2.32.4)
Requirement already satisfied: grpcio<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery-storage) (1.80.0)
Requirement already satisfied: proto-plus<2.0.0,>=1.22.3 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery-storage) (1.28.0)
Requirement already satisfied: protobuf<8.0.0,>=4.25.8 in /usr/local/lib/python3.12/dist-packages (from google-cloud-bigquery-storage) (5.29.6)
Requirement already satisfied: googleapis-common-protos<2.0.0,>=1.63.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core<3.0.0,>=2.15.0->pandas-gbq) (1.75.0)
Requirement already satisfied: grpcio-status<2.0.0,>=1.33.2 in /usr/local/lib/python3.12/dist-packages (from google-api-core[grpc]<3.0.0,>=2.11.1->google-cloud-bigquery) (1.71.2)
Requirement already satisfied: pyasn1-modules>=0.2.1 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.14.1->pandas-gbq) (0.4.2)
Requirement already satisfied: rsa<5,>=3.1.4 in /usr/local/lib/python3.12/dist-packages (from google-auth>=2.14.1->pandas-gbq) (4.9.1)
Requirement already satisfied: requests-oauthlib>=0.7.0 in /usr/local/lib/python3.12/dist-packages (from google-auth-oauthlib>=0.7.0->pandas-gbq) (2.0.0)
Requirement already satisfied: google-crc32c<2.0.0,>=1.0.0 in /usr/local/lib/python3.12/dist-packages (from google-resumable-media<3.0.0,>=2.0.0->google-cloud-bigquery) (1.8.0)
Requirement already satisfied: typing-extensions~=4.12 in /usr/local/lib/python3.12/dist-packages (from grpcio<2.0.0,>=1.33.2->google-cloud-bigquery-storage) (4.15.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.3->pandas-gbq) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas>=1.5.3->pandas-gbq) (2026.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil<3.0.0,>=2.8.2->google-cloud-bigquery) (1.17.0)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.4.7)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (3.15)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests<3.0.0,>=2.21.0->google-cloud-bigquery) (2026.5.20)
Requirement already satisfied: pyasn1<0.7.0,>=0.6.1 in /usr/local/lib/python3.12/dist-packages (from pyasn1-modules>=0.2.1->google-auth>=2.14.1->pandas-gbq) (0.6.3)
Requirement already satisfied: oauthlib>=3.0.0 in /usr/local/lib/python3.12/dist-packages (from requests-oauthlib>=0.7.0->google-auth-oauthlib>=0.7.0->pandas-gbq) (3.3.1)
Downloading pandas_gbq-0.35.0-py3-none-any.whl (50 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.8/50.8 kB 3.5 MB/s eta 0:00:00
Downloading psutil-7.2.2-cp36-abi3-manylinux2010_x86_64.manylinux_2_12_x86_64.manylinux_2_28_x86_64.whl (155 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 155.6/155.6 kB 11.7 MB/s eta 0:00:00
Installing collected packages: psutil, pandas-gbq
  Attempting uninstall: psutil
    Found existing installation: psutil 5.9.5
    Uninstalling psutil-5.9.5:
      Successfully uninstalled psutil-5.9.5
  Attempting uninstall: pandas-gbq
    Found existing installation: pandas-gbq 0.30.0
    Uninstalling pandas-gbq-0.30.0:
      Successfully uninstalled pandas-gbq-0.30.0
Successfully installed pandas-gbq-0.35.0 psutil-7.2.2

In [2]:
import pandas as pd
import pandas_gbq as pd_gbq
import numpy as np
from google.colab import auth
auth.authenticate_user()
print('authenticated')

authenticated

In [3]:
from google.cloud import bigquery
query = """
  SELECT * FROM `Latihan.Full_data`
"""
project_id = 'minitask-1'

In [13]:
pd.set_option('display.max_rows', 50)
pd.set_option('display.max_columns', None)
pd.options.display.float_format = '{:,.2f}'.format

In [5]:
df = pd_gbq.read_gbq(query, project_id = project_id)
df.info()
# ada beberapa kolom yang kosong (10000/22812)

Downloading: 100%|██████████|
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22812 entries, 0 to 22811
Data columns (total 41 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   transaction_id        22812 non-null  object
 1   order_id              22812 non-null  object
 2   order_date            22812 non-null  datetime64[us, UTC]
 3   customer_id           22812 non-null  object
 4   channel_type          22812 non-null  object
 5   sku_id                22812 non-null  object
 6   quantity              22812 non-null  Int64
 7   price                 22812 non-null  Int64
 8   before_discount       22812 non-null  Int64
 9   discount_item         22812 non-null  Int64
 10  after_discount        22812 non-null  Int64
 11  is_gross              22812 non-null  Int64
 12  is_valid              22812 non-null  Int64
 13  is_net                22812 non-null  Int64
 14  customer_name         22812 non-null  object
 15  customer_type         22812 non-null  object
 16  dob                   22812 non-null  dbdate
 17  province              22812 non-null  object
 18  registration_channel  22812 non-null  object
 19  registration_date     22812 non-null  dbdate
 20  category              22812 non-null  object
 21  brand                 22812 non-null  object
 22  product               22812 non-null  object
 23  variant               22812 non-null  object
 24  sku_name              22812 non-null  object
 25  cogs                  22812 non-null  Int64
 26  channel_source        10000 non-null  object
 27  funnel_id             10000 non-null  object
 28  funnel_date           10000 non-null  datetime64[us, UTC]
 29  status                10000 non-null  object
 30  event                 10000 non-null  object
 31  transaction_date      22812 non-null  datetime64[us, UTC]
 32  payment_code          22812 non-null  object
 33  before_tax            22812 non-null  Int64
 34  tax                   22812 non-null  float64
 35  after_tax             22812 non-null  float64
 36  shipping_cost         22812 non-null  Int64
 37  transaction_discount  22812 non-null  Int64
 38  total_paid            22812 non-null  float64
 39  payment_method        22812 non-null  object
 40  rn                    22812 non-null  Int64
dtypes: Int64(13), datetime64[us, UTC](3), dbdate(2), float64(3), object(20)
memory usage: 7.4+ MB

In [6]:
#mengisi null values dengan data agar data mudah dianalisa
#setelah diamati banyak purchasing terjadi namun tidak ada di data funnel maka diberikan keterangan non funnel untuk transaksi seperti itu
df['channel_source'] = df['channel_source'].fillna('Non_Funnel')
df['funnel_id'] = df['funnel_id'].fillna('Non_Funnel')
df['funnel_date'] = pd.to_datetime(df['funnel_date'].fillna('unknown'), errors = 'coerce')
df['event'] = df['event'].fillna('Non_Funnel')
df

,transaction_id,order_id,order_date,customer_id,channel_type,sku_id,quantity,price,before_discount,discount_item,after_discount,is_gross,is_valid,is_net,customer_name,customer_type,dob,province,registration_channel,registration_date,category,brand,product,variant,sku_name,cogs,channel_source,funnel_id,funnel_date,status,event,transaction_date,payment_code,before_tax,tax,after_tax,shipping_cost,transaction_discount,total_paid,payment_method,rn
0,TX0000001,ORD0000001-1,2024-05-16 17:53:01+00:00,CUST03079,Play Store,SKU01954,4,102468,409872,31844,378028,1,1,1,Jamal Puspasari,Student,2003-03-04,Kalimantan Timur,Website,2023-09-15,Books & Stationery,Random House,Novel,Standard,Random House Novel Standard (SKU01954),61801,Play Store,CHN8567676,2024-05-16 17:53:01+00:00,Purchase,Click to Buy,2024-05-16 17:53:01+00:00,PM001,409872,"37,802.80","447,674.80",16222,0,"463,896.80",Digital Wallet,1
1,TX0000002,ORD0000002-1,2020-05-23 15:44:12+00:00,CUST01021,Website,SKU00853,1,228213,228213,0,228213,1,1,1,Candra Rahayu,Undergraduate,1996-12-25,Jawa Tengah,Offline Store,2020-04-15,Beauty & Personal Care,NYX,Sunscreen,Liquid,NYX Sunscreen Liquid (SKU00853),190380,Website,CHN1114140,2020-05-23 15:44:12+00:00,Purchase,Organic,2020-05-23 15:44:12+00:00,PM002,228213,"22,821.30","251,034.30",24690,0,"275,724.30",Virtual Account,1
2,TX0000003,ORD0000003-1,2020-12-03 23:02:48+00:00,CUST02197,Website,SKU04650,2,257424,514848,0,514848,1,1,0,Laras Winarsih,Entrepreneur,1987-04-09,Sumatera Utara,Mobile App,2020-11-01,Toys & Games,Fisher Price,Board Game,Mini,Fisher Price Board Game Mini (SKU04650),179415,Website,CHN5037569,2020-12-03 23:02:48+00:00,Purchase,Click to Buy,2020-12-03 23:02:48+00:00,PM001,25627265,"2,560,263.00","28,187,528.00",9043,0,"28,196,571.00",Digital Wallet,1
3,TX0000003,ORD0000003-2,2020-12-03 23:02:48+00:00,CUST02197,Website,SKU03226,1,207677,207677,24635,183042,1,1,1,Laras Winarsih,Entrepreneur,1987-04-09,Sumatera Utara,Mobile App,2020-11-01,Fashion & Footwear,Vans,Jeans,Regular,Vans Jeans Regular (SKU03226),164662,Non_Funnel,Non_Funnel,NaT,None,Non_Funnel,2020-12-03 23:02:48+00:00,PM001,25627265,"2,560,263.00","28,187,528.00",9043,0,"28,196,571.00",Digital Wallet,1
4,TX0000003,ORD0000003-3,2020-12-03 23:02:48+00:00,CUST02197,Website,SKU01922,2,12452370,24904740,0,24904740,1,1,1,Laras Winarsih,Entrepreneur,1987-04-09,Sumatera Utara,Mobile App,2020-11-01,Electronics,LG,Printer,Ultra,LG Printer Ultra (SKU01922),8275362,Non_Funnel,Non_Funnel,NaT,None,Non_Funnel,2020-12-03 23:02:48+00:00,PM001,25627265,"2,560,263.00","28,187,528.00",9043,0,"28,196,571.00",Digital Wallet,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
22807,TX0012997,ORD0012997-4,2021-01-03 20:08:55+00:00,CUST02043,Offline Store,SKU04647,3,7880992,23642976,0,23642976,1,1,1,Nilam Mulyani,Other,1982-11-26,Kalimantan Barat,Mobile App,2019-12-19,Gaming Gear,Logitech,Gaming Keyboard,Limited,Logitech Gaming Keyboard Limited (SKU04647),5723885,Non_Funnel,Non_Funnel,NaT,None,Non_Funnel,2021-01-03 20:08:55+00:00,PM003,31861665,"3,186,166.50","35,047,831.50",14823,0,"35,062,654.50",QRIS Payment,1
22808,TX0012998,ORD0012998-1,2024-03-02 16:55:33+00:00,CUST01425,Offline Store,SKU03906,1,35043,35043,3953,31090,1,1,1,Aris Prasetyo,Teacher,1974-11-22,Sulawesi Utara,Offline Store,2021-08-21,Food & Beverage,Ultra Milk,Beverage,Regular,Ultra Milk Beverage Regular (SKU03906),27387,Non_Funnel,Non_Funnel,NaT,None,Non_Funnel,2024-03-02 16:55:33+00:00,PM002,35043,"3,109.00","38,152.00",13412,0,"51,564.00",Virtual Account,1
22809,TX0012999,ORD0012999-1,2024-03-10 02:57:54+00:00,CUST02307,Offline Store,SKU02941,2,40986,81972,0,81972,1,1,1,Sadina Rahayu,Undergraduate,1997-10-13,Aceh,Mobile App,2020-05-10,Food & Beverage,Coca Cola,Beverage,Organic,Coca Cola Beverage Organic (SKU02941),28370,Non_Funnel,Non_Funnel,NaT,None,Non_Funnel,2024-03-10 02:57:54+00:00,PM005,120219,"12,021.90","132,240.90",15215,0,"147,455.90",Credit Card Payment,1
22810,TX0012999,ORD0012999-2,2024-03-10 02:57:54+00:00,CUST02307,Offline Store,SKU03624,1,38247,38247,0,38247,1,1,1,Sadina Rahayu,Undergraduate,1997-10-13,Aceh,Mobile App,2020-05-10,Food & Beverage,Coca Cola,Beverage,Zero,Coca Cola Beverage Zero (SKU03624),32682,Non_Funnel,Non_Funnel,NaT,None,Non_Funnel,2024-03-10 02:57:54+00:00,PM005,120219,"12,021.90","132,240.90",15215,0,"147,455.90",Credit Card Payment,1
22811,TX0013000,ORD0013000-1,2023-03-16 22:24:27+00:00,CUST02801,Offline Store,SKU00102,1,1781244,1781244,94804,1686440,1,1,1,Hana Budiman,Other,1962-07-11,DKI Jakarta,Mobile App,2021-09-20,Kitchen Appliances,Cosmos,Microwave Oven,Smart,Cosmos Microwave Oven Smart (SKU00102),1319580,Non_Funnel,Non_Funnel,NaT,None,Non_Funnel,2023-03-16 22:24:27+00:00,PM001,1781244,"168,644.00","1,949,888.00",15696,0,"1,965,584.00",Digital Wallet,1

In [ ]:
df['status'].unique()

array(['Purchase', None], dtype=object)

In [ ]:
df.duplicated().sum() #tidak ada data duplikat #sesuai dengan hasil uji di bigquerynya

np.int64(0)

In [ ]:
df.info()
#semua kolom terisi (22812/22812)

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 22812 entries, 0 to 22811
Data columns (total 41 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   transaction_id        22812 non-null  object
 1   order_id              22812 non-null  object
 2   order_date            22812 non-null  datetime64[us, UTC]
 3   customer_id           22812 non-null  object
 4   channel_type          22812 non-null  object
 5   sku_id                22812 non-null  object
 6   quantity              22812 non-null  Int64
 7   price                 22812 non-null  Int64
 8   before_discount       22812 non-null  Int64
 9   discount_item         22812 non-null  Int64
 10  after_discount        22812 non-null  Int64
 11  is_gross              22812 non-null  Int64
 12  is_valid              22812 non-null  Int64
 13  is_net                22812 non-null  Int64
 14  customer_name         22812 non-null  object
 15  customer_type         22812 non-null  object
 16  dob                   22812 non-null  dbdate
 17  province              22812 non-null  object
 18  registration_channel  22812 non-null  object
 19  registration_date     22812 non-null  dbdate
 20  category              22812 non-null  object
 21  brand                 22812 non-null  object
 22  product               22812 non-null  object
 23  variant               22812 non-null  object
 24  sku_name              22812 non-null  object
 25  cogs                  22812 non-null  Int64
 26  channel_source        22812 non-null  object
 27  funnel_id             22812 non-null  object
 28  funnel_date           10000 non-null  datetime64[ns, UTC]
 29  status                10000 non-null  object
 30  event                 22812 non-null  object
 31  transaction_date      22812 non-null  datetime64[us, UTC]
 32  payment_code          22812 non-null  object
 33  before_tax            22812 non-null  Int64
 34  tax                   22812 non-null  float64
 35  after_tax             22812 non-null  float64
 36  shipping_cost         22812 non-null  Int64
 37  transaction_discount  22812 non-null  Int64
 38  total_paid            22812 non-null  float64
 39  payment_method        22812 non-null  object
 40  rn                    22812 non-null  Int64
dtypes: Int64(13), datetime64[ns, UTC](1), datetime64[us, UTC](2), dbdate(2), float64(3), object(20)
memory usage: 7.4+ MB

In [ ]:
#ekspor data ke bigquery
pd_gbq.to_gbq(
    df,
    'Latihan.full_data_cleaned',
    project_id,
    if_exists = 'replace'
)

100%|██████████| 1/1 [00:00<00:00, 7695.97it/s]

In [ ]:
df['is_net'].sum()/df['is_net'].count() * 100

np.float64(87.45397159389795)

In [7]:
df['channel_source'].unique()

array(['Play Store', 'Website', 'Non_Funnel', 'App Store'], dtype=object)

Analsisi statistika deskriptif

In [11]:
df['margin_percentage'] = ((df['after_discount']-df['cogs'])/df['after_discount'])*100
df['cogs_percentage'] =  (df['cogs']/df['after_discount'])*100
df.head(10)

,transaction_id,order_id,order_date,customer_id,channel_type,sku_id,quantity,price,before_discount,discount_item,after_discount,is_gross,is_valid,is_net,customer_name,customer_type,dob,province,registration_channel,registration_date,category,brand,product,variant,sku_name,cogs,channel_source,funnel_id,funnel_date,status,event,transaction_date,payment_code,before_tax,tax,after_tax,shipping_cost,transaction_discount,total_paid,payment_method,rn,margin_percentage,cogs_percentage
0,TX0000001,ORD0000001-1,2024-05-16 17:53:01+00:00,CUST03079,Play Store,SKU01954,4,102468,409872,31844,378028,1,1,1,Jamal Puspasari,Student,2003-03-04,Kalimantan Timur,Website,2023-09-15,Books & Stationery,Random House,Novel,Standard,Random House Novel Standard (SKU01954),61801,Play Store,CHN8567676,2024-05-16 17:53:01+00:00,Purchase,Click to Buy,2024-05-16 17:53:01+00:00,PM001,409872,"37,802.80","447,674.80",16222,0,"463,896.80",Digital Wallet,1,83.65,16.35
1,TX0000002,ORD0000002-1,2020-05-23 15:44:12+00:00,CUST01021,Website,SKU00853,1,228213,228213,0,228213,1,1,1,Candra Rahayu,Undergraduate,1996-12-25,Jawa Tengah,Offline Store,2020-04-15,Beauty & Personal Care,NYX,Sunscreen,Liquid,NYX Sunscreen Liquid (SKU00853),190380,Website,CHN1114140,2020-05-23 15:44:12+00:00,Purchase,Organic,2020-05-23 15:44:12+00:00,PM002,228213,"22,821.30","251,034.30",24690,0,"275,724.30",Virtual Account,1,16.58,83.42
2,TX0000003,ORD0000003-1,2020-12-03 23:02:48+00:00,CUST02197,Website,SKU04650,2,257424,514848,0,514848,1,1,0,Laras Winarsih,Entrepreneur,1987-04-09,Sumatera Utara,Mobile App,2020-11-01,Toys & Games,Fisher Price,Board Game,Mini,Fisher Price Board Game Mini (SKU04650),179415,Website,CHN5037569,2020-12-03 23:02:48+00:00,Purchase,Click to Buy,2020-12-03 23:02:48+00:00,PM001,25627265,"2,560,263.00","28,187,528.00",9043,0,"28,196,571.00",Digital Wallet,1,65.15,34.85
3,TX0000003,ORD0000003-2,2020-12-03 23:02:48+00:00,CUST02197,Website,SKU03226,1,207677,207677,24635,183042,1,1,1,Laras Winarsih,Entrepreneur,1987-04-09,Sumatera Utara,Mobile App,2020-11-01,Fashion & Footwear,Vans,Jeans,Regular,Vans Jeans Regular (SKU03226),164662,Non_Funnel,Non_Funnel,NaT,None,Non_Funnel,2020-12-03 23:02:48+00:00,PM001,25627265,"2,560,263.00","28,187,528.00",9043,0,"28,196,571.00",Digital Wallet,1,10.04,89.96
4,TX0000003,ORD0000003-3,2020-12-03 23:02:48+00:00,CUST02197,Website,SKU01922,2,12452370,24904740,0,24904740,1,1,1,Laras Winarsih,Entrepreneur,1987-04-09,Sumatera Utara,Mobile App,2020-11-01,Electronics,LG,Printer,Ultra,LG Printer Ultra (SKU01922),8275362,Non_Funnel,Non_Funnel,NaT,None,Non_Funnel,2020-12-03 23:02:48+00:00,PM001,25627265,"2,560,263.00","28,187,528.00",9043,0,"28,196,571.00",Digital Wallet,1,66.77,33.23
5,TX0000004,ORD0000004-1,2024-08-12 08:32:49+00:00,CUST01112,App Store,SKU04948,1,1046312,1046312,0,1046312,1,1,1,Marsito Mahendra,Entrepreneur,1982-09-13,Sulawesi Selatan,Offline Store,2022-04-16,Home Decor,Chitose,Wall Art,Vintage,Chitose Wall Art Vintage (SKU04948),768717,App Store,CHN6114579,2024-08-12 08:32:49+00:00,Purchase,Organic,2024-08-12 08:32:49+00:00,PM003,1046312,"104,631.20","1,150,943.20",11312,0,"1,162,255.20",QRIS Payment,1,26.53,73.47
6,TX0000005,ORD0000005-1,2020-11-15 06:13:56+00:00,CUST04805,Play Store,SKU04923,1,139618,139618,0,139618,1,1,1,Warji Maheswara,Other,1968-04-03,Riau,Website,2020-06-20,Health & Wellness,Herbalife,Hand Sanitizer,Kid,Herbalife Hand Sanitizer Kid (SKU04923),108843,Play Store,CHN7852670,2020-11-15 06:13:56+00:00,Purchase,Click to Buy,2020-11-15 06:13:56+00:00,PM006,139618,"13,961.80","153,579.80",15436,0,"169,015.80",PayLater (BNPL),1,22.04,77.96
7,TX0000006,ORD0000006-1,2023-12-02 22:10:22+00:00,CUST03561,Website,SKU03400,1,111214,111214,0,111214,1,1,1,Amelia Prabowo,Undergraduate,2000-05-12,Bali,Website,2020-08-06,Fashion & Footwear,Vans,Hoodie,Regular,Vans Hoodie Regular (SKU03400),93268,Website,CHN6285925,2023-12-02 22:10:22+00:00,Purchase,Organic,2023-12-02 22:10:22+00:00,PM001,529185,"52,918.50","582,103.50",21578,0,"603,681.50",Digital Wallet,1,16.14,83.86
8,TX0000006,ORD0000006-2,2023-12-02 22:10:22+00:00,CUST03561,Website,SKU04905,1,417971,417971,0,417971,1,1,1,Amelia Prabowo,Undergraduate,2000-05-12,Bali,Website,2020-08-06,Fashion & Footwear,Converse,Jacket,Slim,Converse Jacket Slim (SKU04905),312305,Non_Funnel,Non_Funnel,NaT,None,Non_Funnel,2023-12-02 22:10:22+00:00,PM001,529185,"52,918.50","582,103.50",21578,0,"603,681.50",Digital Wallet,1,25.28,74.72
9,TX0000007,ORD0000007-1,2024-12-08 08:56:50+00:00,CUST02993,Play Store,SKU01746,1,410588,410588,0,410588,1,1,1,Queen Pratama,Undergraduate,1995-11-27,Kalimantan Barat,Website,2021-12-29,Kitchen Appliances,Maspion,Baking Tray,Standard,Maspion Baking Tray Standard (SKU01746),256208,Play Store,CHN9023399,2024-12-08 08:56:50+00:00,Purchase,Organic,2024-12-08 08:56:50+00:00,PM003,410588,"41,058.80","451,646.80",13507,0,"465,153.80",QRIS Payment,1,37.60,62.40

In [27]:
groupby = df.groupby('category').agg({
    'after_discount' : ['mean','median','max','min'],
    'margin_percentage' : ['mean','median','max','min'],
    'cogs' : ['mean','median','max','min'],
    'cogs_percentage' : ['mean','median','max','min']
}).style.format(lambda x:"{:,.2f}".format(x))
groupby

**ANALISIS CUSTOMER RETENTION AND LOYALITY**

In [ ]:
customer = """
  select
    customer_name,
    max(order_date) as last_transaction,
    count(distinct transaction_id) as freq_transaction,
    sum(after_discount) as volume
  from `Latihan.full_data_cleaned`
  where is_net = 1 and is_valid = 1
  group by 1
"""

In [ ]:
#mengunduh data customer untuk diolah
segmentation = pd_gbq.read_gbq(customer, project_id = project_id)
segmentation

Downloading: 100%|██████████|

          customer_name          last_transaction  freq_transaction     volume
0      Dinda Situmorang 2024-03-18 17:08:12+00:00                 2   23372448
1         Bakda Ramadan 2024-03-21 15:41:38+00:00                 2   20508912
2       Mariadi Sudiati 2022-08-23 22:37:40+00:00                 2  143395771
3      Cengkal Yulianti 2024-09-15 23:26:15+00:00                 3    6453729
4           Ega Nugroho 2024-07-28 22:02:39+00:00                 4   18698821
...                 ...                       ...               ...        ...
4569    Dalimin Permata 2022-06-28 21:40:08+00:00                 1    1113884
4570  Cahyadi Lailasari 2022-10-03 19:22:41+00:00                 3    1092697
4571     Jumadi Wahyuni 2020-05-24 15:45:30+00:00                 1  141975952
4572      Mutia Saputra 2024-03-26 07:17:17+00:00                 7    4479567
4573      Zahra Pratama 2020-07-10 21:41:13+00:00                 2    5139441

[4574 rows x 4 columns]

In [ ]:
#menetapkan status di setiap metrik
segmentation['recency_status'] = pd.qcut(segmentation['last_transaction'], q = 2, labels = ['Lama','Baru'])
segmentation['freq_status'] = pd.qcut(segmentation['freq_transaction'], q = 2, labels = ['Rendah','Tinggi'])
segmentation['volume_status'] = pd.qcut(segmentation['volume'], q = 2, labels = ['Rendah', 'Tinggi'])
segmentation

,customer_name,last_transaction,freq_transaction,volume,recency_status,freq_status,volume_status
0,Dinda Situmorang,2024-03-18 17:08:12+00:00,2,23372448,Baru,Rendah,Tinggi
1,Bakda Ramadan,2024-03-21 15:41:38+00:00,2,20508912,Baru,Rendah,Tinggi
2,Mariadi Sudiati,2022-08-23 22:37:40+00:00,2,143395771,Lama,Rendah,Tinggi
3,Cengkal Yulianti,2024-09-15 23:26:15+00:00,3,6453729,Baru,Tinggi,Tinggi
4,Ega Nugroho,2024-07-28 22:02:39+00:00,4,18698821,Baru,Tinggi,Tinggi
...,...,...,...,...,...,...,...
4569,Dalimin Permata,2022-06-28 21:40:08+00:00,1,1113884,Lama,Rendah,Rendah
4570,Cahyadi Lailasari,2022-10-03 19:22:41+00:00,3,1092697,Lama,Tinggi,Rendah
4571,Jumadi Wahyuni,2020-05-24 15:45:30+00:00,1,141975952,Lama,Rendah,Tinggi
4572,Mutia Saputra,2024-03-26 07:17:17+00:00,7,4479567,Baru,Tinggi,Rendah
4573,Zahra Pratama,2020-07-10 21:41:13+00:00,2,5139441,Lama,Rendah,Tinggi

In [ ]:
#menetapkan kondisi
condition = [
    (segmentation['recency_status'] == 'Baru') & (segmentation['freq_status'] == 'Tinggi') & (segmentation['volume_status'] == 'Tinggi'),
    (segmentation['recency_status'] == 'Baru') & (segmentation['freq_status'] == 'Tinggi') & (segmentation['volume_status'] == 'Rendah'),
    (segmentation['recency_status'] == 'Baru') & (segmentation['freq_status'] == 'Rendah') & (segmentation['volume_status'] == 'Tinggi'),
    (segmentation['recency_status'] == 'Baru') & (segmentation['freq_status'] == 'Rendah') & (segmentation['volume_status'] == 'Rendah'),
    (segmentation['recency_status'] == 'Lama') & (segmentation['freq_status'] == 'Tinggi') & (segmentation['volume_status'] == 'Tinggi'),
    (segmentation['recency_status'] == 'Lama' ) & (segmentation['freq_status'] == 'Tinggi') & (segmentation['volume_status'] == 'Rendah'),
    (segmentation['recency_status'] == 'Lama') & (segmentation['freq_status'] == 'Rendah') & (segmentation['volume_status'] == 'Tinggi'),
    (segmentation['recency_status'] == 'Lama') & (segmentation['freq_status'] == 'Rendah') & (segmentation['volume_status'] == 'Rendah')
]

In [ ]:
#membuat label
labels = [
    'Champions',
    'Loyal Small Buyers',
    'Potential loyalist',
    'Triallist',
    'At Risk',
    'Churning Customers',
    'Dormant Spenders',
    'Lost Customers'
]

In [ ]:
segmentation['RFM_status'] = np.select(condition, labels, default = 'No Status') #penggabungan kategori dan label
segmentation

,customer_name,last_transaction,freq_transaction,volume,recency_status,freq_status,volume_status,RFM_status
0,Dinda Situmorang,2024-03-18 17:08:12+00:00,2,23372448,Baru,Rendah,Tinggi,Potential loyalist
1,Bakda Ramadan,2024-03-21 15:41:38+00:00,2,20508912,Baru,Rendah,Tinggi,Potential loyalist
2,Mariadi Sudiati,2022-08-23 22:37:40+00:00,2,143395771,Lama,Rendah,Tinggi,Dormant Spenders
3,Cengkal Yulianti,2024-09-15 23:26:15+00:00,3,6453729,Baru,Tinggi,Tinggi,Champions
4,Ega Nugroho,2024-07-28 22:02:39+00:00,4,18698821,Baru,Tinggi,Tinggi,Champions
...,...,...,...,...,...,...,...,...
4569,Dalimin Permata,2022-06-28 21:40:08+00:00,1,1113884,Lama,Rendah,Rendah,Lost Customers
4570,Cahyadi Lailasari,2022-10-03 19:22:41+00:00,3,1092697,Lama,Tinggi,Rendah,Churning Customers
4571,Jumadi Wahyuni,2020-05-24 15:45:30+00:00,1,141975952,Lama,Rendah,Tinggi,Dormant Spenders
4572,Mutia Saputra,2024-03-26 07:17:17+00:00,7,4479567,Baru,Tinggi,Rendah,Loyal Small Buyers
4573,Zahra Pratama,2020-07-10 21:41:13+00:00,2,5139441,Lama,Rendah,Tinggi,Dormant Spenders

In [ ]:
segmentation_summary = segmentation.groupby('RFM_status').agg({
    'customer_name': 'count',
    'freq_transaction': ['mean','max'],
    'volume': ['mean', 'max']
})
segmentation_summary

                   customer_name freq_transaction            volume
                           count             mean max          mean        max
RFM_status
At Risk                      492             3.66   7 35,707,143.03  362661694
Champions                   1037             4.22   9 37,040,766.16  453652233
Churning Customers           228             3.36   7  2,487,506.17    4485877
Dormant Spenders             477             1.60   2 29,363,158.48  355865160
Lost Customers              1090             1.41   2  1,294,217.28    4495532
Loyal Small Buyers           372             3.44   7  2,547,131.70    4498611
Potential loyalist           281             1.83   2 29,839,330.69  440963824
Triallist                    597             1.61   2  1,521,681.30    4427771

In [ ]:
pd_gbq.to_gbq(
    segmentation,
    'Latihan.segmentation',
    project_id,
    if_exists = 'replace'
)

100%|██████████| 1/1 [00:00<00:00, 5059.47it/s]

In [ ]:
sg_23 = segmentation.groupby('RFM_status').agg({
    'customer_name': 'count',
    'freq_transaction': ['mean','max'],
    'volume': ['mean', 'max']
})

sg_23

                   customer_name freq_transaction            volume
                           count             mean max          mean        max
RFM_status
At Risk                      492             3.66   7 35,707,143.03  362661694
Champions                   1037             4.22   9 37,040,766.16  453652233
Churning Customers           228             3.36   7  2,487,506.17    4485877
Dormant Spenders             477             1.60   2 29,363,158.48  355865160
Lost Customers              1090             1.41   2  1,294,217.28    4495532
Loyal Small Buyers           372             3.44   7  2,547,131.70    4498611
Potential loyalist           281             1.83   2 29,839,330.69  440963824
Triallist                    597             1.61   2  1,521,681.30    4427771

In [ ]:
for i in sg_23.columns:
  print(i)

('customer_name', 'count')
('freq_transaction', 'mean')
('freq_transaction', 'max')
('volume', 'mean')
('volume', 'max')

In [ ]:
segmentation_summary.columns = ['_'.join(col).strip() if isinstance(col, tuple) else str(col) for col in segmentation_summary.columns]

In [ ]:
pd_gbq.to_gbq(
    segmentation_summary,
    'Latihan.segmentation_summary',
    project_id,
    if_exists = 'replace'
)

100%|██████████| 1/1 [00:00<00:00, 9039.45it/s]

In [ ]:
funneling = """
  with f as (
  select
    count(case when status = 'Click' then 1 end) as c,
    count(case when status = 'Viewed' then 1 end) as V,
    count(case when status = 'Add to Cart' then 1 end) as atc,
    count(case when status = 'Purchase' then 1 end) as p,
  from `Latihan.funnel_detail_cleaned`)
  select
    round((c+v+atc+p)/(c+v+atc+p)*100,2) as click,
    round(((v+atc+p)/(c+v+atc+p))*100,2) as Viewperc,
    round(((atc+p)/(v+atc+p))*100,2) as addtocartperc,
    round((p/(atc+p))*100,2) as purchperc
  from f
"""

In [ ]:
convertion_rate = pd_gbq.read_gbq(funneling, project_id = project_id)
transposed_convertion_rate = convertion_rate.T
transposed_convertion_rate.reset_index(inplace = True)
transposed_convertion_rate.columns = ['funnel_stage' ,'Percentage']
transposed_convertion_rate

Downloading: 100%|██████████|

    funnel_stage  Percentage
0          click      100.00
1       Viewperc       52.39
2  addtocartperc       37.91
3      purchperc       12.28

In [ ]:
pd_gbq.to_gbq(
    transposed_convertion_rate,
    'Latihan.convertion_rate',
    project_id,
    if_exists = 'replace'
)

100%|██████████| 1/1 [00:00<00:00, 8525.01it/s]